#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# lint js/ts files + format with prettier
echo 🧿 Running file linter and formatter...
npx lint-staged --concurrent false
echo ''

# validate configs
echo 🧿 Running marketplace config validator...
yarn validate:marketplace

echo 🧿 Running featured networks config validator...
yarn validate:featured-networks

echo 🧿 Running footer links config validator...
yarn validate:footer-links

# format svg
echo 🧿 Running svg formatter...
for file in `git diff --diff-filter=ACMRT --cached --name-only | grep ".svg\$"`
    do 
        echo "Formatting $file" 
        npx svgo -q $file 
        git add $file
    done

echo ✅ All pre-commit jobs are done